version: 2

models:
  - name: stg_users 
    description: Contains our app users
  - name: stg_events
    description: Contains events information
  - name: stg_products
    description: Contains product information
  - name: stg_order_items
    description: Contains ordered product information
  - name: stg_promos
    description: Contains promotion information
  - name: stg_addresses
    description: contains customer address information
  - name: stg_orders 
    description: contains customer orders information