version: 2

models:
  - name: fct_page_views
    description: "Fact table for page view information by user."
    tests: 
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - page_url
    columns:
      - name: number_of_views
        description: "Number of times the user has viewed the page."
        tests:
          - positive_values
  - name: fact_sessions_events
    description: for each session, whether it had an event of each type
    columns: 
      - name: session_id
        tests: 
          - unique
          - not_null
      - name: has_page_view
      - name: has_add_to_cart
      - name: has_checkout
      - name: has_package_shipped
  - name: funnel_sessions
    description: for each session, whether it is in each funnel level
    columns: 
      - name: session_id
        tests: 
          - unique
          - not_null
      - name: level_page_view
      - name: level_add_to_cart
      - name: level_checkout
  